name: Deploy Workflow State to Novu

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Sync State to Novu
        uses: novuhq/actions-novu-sync@v0.0.4
        with:
          secret-key: ${{ secrets.NOVU_SECRET_KEY }}
          bridge-url: https://93ae7363-6ff8-4096-a52d-2088a10e0b7f.ntfr.dev/api/novu
          api-url: https://dev.api.novu.co
